### ISSUE TITLE
global.fncstatic.com breaks foxnews.com layout

### ISSUE THREAD

**Issue by terrorist96** [EFForg/privacybadger#1291]
http://www.foxnews.com/

`global.fncstatic.com` breaks site layout. Needs to be moved from red to yellow.

**Comment by terrorist96** [comment]
See #1031 as well.

**Comment by ghostwords** [comment]
This bug should be fixed in Privacy Badger version 2017.6.13.1 (by #1403 and #1428). Please let me know if you run into it again with the new version.

**Comment by terrorist96** [comment]
@ghostwords This is not fixed. `global.fncstatic.com` is still being blocked by default for me. (All other issues that were closed by 1403/1428 that I've gone through so far have been fixed, but this one isn't.)

**Comment by raphapp** [comment]
This is not fixed.

global fncstatic social fox styles orion
http://www.foxnews.com/politics/2017/07/12/white-house-goes-on-offense-slams-dnc-clintons-for-collusion.html
https://search.yahoo.com/yhs/errorhandler?hspart=gt&hsimp=yhse-gt&q=global.fncstatic.com%2Fstatic%2Forion%2Fstyles%2Fimg%2Ffox-news%2Fbg%2Fsocial-&type=808263

**Comment by terrorist96** [comment]
@cowlicks It's not fixed.

**Comment by ghostwords** [comment]
This is fixed in master by 6e97c548a5f9fb8c4d584ade023b01c388d62675, which marks `foxnews.com`, `foxbusiness.com` and `fncstatic.com` as first parties with respect to each other. The fix hasn't gone out yet though. Sorry for the confusion!

**Comment by terrorist96** [comment]
I wish it were possible to have the update pushed out without having to wait for a new build of the extension, similar to filter-lists of uBlock Origin/ABP/etc. that check the URL for a new version.

**Comment by ghostwords** [comment]
Related: #795, #1487.

**Comment by ghostwords** [comment]
This should now be fixed in production with [Privacy Badger 2017.7.24](https://github.com/EFForg/privacybadger/releases/tag/release-2017.7.24).
