### ISSUE TITLE
Various site breakages (Wordpress Admin, eBay) in Firefox

### ISSUE THREAD

**Issue by flexerd** [EFForg/privacybadger#1295]
With Privacy Badger installed, and site whitelisted. 
Wordpress admin does not refresh to the new URL after an update.
To recreate: Open Wordpress admin, Edit a post, then navigate to another section such as Appearance>Menu. URL changes, yet page remains on the same page.
This could effect other PHP driven websites.
Upon disabling PB completely in FF, site functions normally.
Does not effect Chrome.

**Comment by ghostwords** [comment]
Disabling Badger for the site not working properly in Firefox was mentioned in #1287. Updating the URL but not actually loading the page in Firefox first came up in #1266.

**Comment by ghostwords** [comment]
What versions of Privacy Badger and Firefox do you have? Is Badger blocking any domains in WordPress Admin?

**Comment by flexerd** [comment]
No blocked domain in admin.
FF: 52.0.2 (32-bit)
Privacy Badger 2017.3.28

**Comment by Vetrikay** [comment]
Same issue on for example My Ebay -> Summary page (https://www.ebay.com/myb/Summary)

To recreate: Go to My Ebay -> Summary page, click on "Messages", page does not load, Firefox visually still shows the "Summary" page, but clicking on anything does not work. The address bar is changed and shows the correct link for the "Messages" page. Page refresh (either F5 or CTRL + F5) works and shows the correct page. Privacy Badger is off for eBay. Disabling the addon in Firefox fixes the problem. 

Using Privacy Badger 2017.3.28 and Firefox to 52.0.2

I already reported it through the add-on directly, not sure if you've got it.

**Comment by ghostwords** [comment]
From a support email:
> I recently discovered that when PB is enabled in firefox it causes
> problems at ebay.co.uk. The search function is not working properly. It
> gets stuck. Also ebay functions like "worldwide" or "sort by" are not
> working. That happens even if PB is disabled for the site. However, if I
> completely disable the addon for firefox, ebay works fine.

**Comment by voidstarstar** [comment]
Both the Wordpress and eBay examples above seem to require an account to reproduce.

For easier troubleshooting, I'm also able to reproduce this issue simply by going to http://www.ebay.com/ and searching for anything without needing to log in.  As previously mentioned, the address bar changes, but the page does not actually update unless reloaded.  I've noticed similar issues with *many* links on eBay, all of which are easily reproducible.


Firefox 53.0
Privacy Badger 2017.4.19.1

**Comment by ghostwords** [comment]
Does this happen in a fresh profile with only Privacy Badger installed?

**Comment by voidstarstar** [comment]
This bug is tricky.  I am unable to reproduce it in a fresh profile with only Privacy Badger installed.

In an old profile, I think I can reliably replicate the bug.  Disabling the extension will cause the bug to immediately disappear for all subsequent attempts.  Enabling the extension again will cause the bug to reappear.  This test was done without restarting the browser.

This bug also seems to affect 2 other computers that I support with similar configurations and extensions.

**Comment by ghostwords** [comment]
Could it be the combination of Privacy Badger and another add-on that causes these issues to happen?

**Comment by voidstarstar** [comment]
It's possible.  I've tried to add all of the extensions I have installed to a fresh profile, but it still does not seem to cause the bug.

I've also tried disabling all other extensions on the old profile.

Could a new version of firefox also be responsible for a breaking change?  Maybe new profiles are set up with a valid config, but old profiles use a config that cause new firefox versions to exhibit this bug?

**Comment by voidstarstar** [comment]
Ok, I may have figured it out.  Ubuntu adds an "Ubuntu Modifications" extension by default to firefox profiles.  In my old profile, the bug exists when all extensions are disabled except for Ubuntu Modifications and Privacy Badger.  Upon disabling either of these extensions, the bug goes away.  (This extension has also been known to cause issues with some other popular extensions in the past.)

For some reason, this does not seem to affect new firefox profiles, however.

Perhaps @flexerd and @Vetrikay can confirm which OS they are using?

**Comment by flexerd** [comment]
Hello
I am using windows 10. Current FF.
Haven't tried creating a new profile with just extension. I can try.
Thanks

**Comment by flexerd** [comment]
Tried on FF Developer Edition with only extension being PB, and there was no issue.

**Comment by cowlicks** [comment]
I can't reproduce this on ebay with FF 54 and PB 2017.6.13.1

@flexerd is this still a problem for you?

**Comment by flexerd** [comment]
hi @cowlicks Just updated to FF 54 and have  PB 2017.6.13. Same problem. 

When on my Wordpress admin the URL changes but the page does not refresh, but remain on the former page. Only refreshing the page manually bring up the new page. WP is up to date. I have tried this on two different servers and Wordpress installs.

Daveed

**Comment by ghostwords** [comment]
@flexerd Is this an issue if you load only the following test extension I made (disabling all other add-ons for now)? https://github.com/EFForg/privacybadger/files/1079120/firefox_webext_onunload_bug_demo.zip

**Comment by ghostwords** [comment]
To load the above add-on in Firefox, unzip the archive somewhere, visit `about:debugging`, click on Load Temporary Add-on, and pick the `manifest.json` file inside the unzipped folder.

**Comment by flexerd** [comment]
Done
![debugging](https://user-images.githubusercontent.com/15328506/27205293-f6b9baca-51fd-11e7-8d74-c6b240ee8d87.PNG)
The issue did not appear.

Daveed

**Comment by flexerd** [comment]
@ghostwords The issue did not appear

**Comment by phusg** [comment]
I had the same issue of URL changing but ebay page not loading. Ebay only worked when I completely disabled Privacy badger. In the end I went for the refresh firefox https://support.mozilla.org/en-US/kb/refresh-firefox-reset-add-ons-and-settings, reinstalled my add-ons https everywhere, ublock origin, passsec+ and privacy badger and now the issue is gone. I did lose some settings and probably some other stuff I'll bump into the coming days, but at least the issue is gone.

**Comment by flexerd** [comment]
@ghostwords I also did the refresh firefox as @phusg suggested and it looks liek the trouble has been fixed.

**Comment by ghostwords** [comment]
Nice, I'm glad there is a workaround!

For whoever still has the issue, could you try (temporarily) disabling all add-ons and installing my [test add-on](https://github.com/EFForg/privacybadger/files/1079120/firefox_webext_onunload_bug_demo.zip) and then reloading pages to see if the issue is still there?

To load the test add-on in Firefox, unzip its archive somewhere, visit `about:debugging`, click on Load Temporary Add-on, and pick the `manifest.json` file inside the unzipped folder.

**Comment by Muad-Dib** [comment]
I'm experiencing this issue with P.B. as well on ebay particularly when using the messaging centre (I haven't encountered any problems elsewhere as yet).  Ghostwords: I followed your instructions and tried your temporary plugin as requested above and the behaviour is unchanged i.e. still broken.

**Comment by flexerd** [comment]
@Muad-Dib did you try the refresh firefox route? I am expriencing zero issues since I did it.

**Comment by ghostwords** [comment]
Hi @Muad-Dib, your symptoms (on navigation URL updates but the page does not, disabling for the site doesn't help, Firefox-only) and fact that you were able to reproduce using no add-ons except for my test add-on suggest you are running into the same Firefox bug as #1438, which we opened an issue for with Firefox here: https://bugzilla.mozilla.org/show_bug.cgi?id=1373776.

**Comment by Muad-Dib** [comment]
@flexerd: No I haven't. Obviously I'm interested in a solution but for now I'm curious as to what's changed exactly to break what has thus far been a robust and reliable set-up.

@ghostwords: Thanks for link to bug.  I'm in the process of testing this on a few other platforms with the same profile.  Will update tomorrow.

**Comment by Muad-Dib** [comment]
OK, here are my results.  Obviously I had limited time to test permutations, but some interesting findings nonetheless.  All tests verified against ability to access ebay messaging:

= NOT WORKING =
1. - Firefox 54.0 on Ubuntu 16.04 (Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:54.0) Gecko/20100101 Firefox/54.0) (PB v2017.7.24) using current profile.

2. - Firefox 54.0.1 on Windows 8 (Mozilla/5.0 (Windows NT 6.3; Win64; x64; rv:54.0) Gecko/20100101 Firefox/54.0) (PB v2017.7.24) using current profile.

3. - Firefox 52.2.1 ESR on Windows XP (Mozilla/5.0 (Windows NT 5.1; rv:52.0) Gecko/20100101 Firefox/52.0) (PB v2017.7.24) using current profile.

= WORKING = 
4. - Firefox 45.9.0 ESR on Windows XP (Mozilla/5.0 (Windows NT 5.1; rv:45.0) Gecko/20100101 Firefox/45.0) (PB v2017.3.28) using current profile.

5. - Firefox 54.0 on Ubuntu 16.04, type about:profiles, create a new (empty) profile then install just onload_bug_demo.zip

6. - Using the above, install full version P.Bb v2017.07.24

7. - Firefox 54.0 on Ubuntu 16.04 using current profile, type about:support, select refresh firefox (creates new profile with no addons but migrates all settings), then fresh install all currently used addons


= Summary =

a. Using my current profile, the bug will manifest:
- when using any current Firefox versions (>50) on any operating system
- only with P.B. enabled, irrespective of the total number of other addons present and whether they are enabled or disabled

b. Using my current profile with Firefox v45.0 ESR (and possibly earlier) works fine

c. a clean or 'refreshed' current profile with all currently used addons present and enabled also works fine in current Firefox versions


= My Conclusions =

i. Something changed in Firefox rendering code, certainly between the last two ESR versions and remains in current release versions.

ii. Reverting to an earlier Firefox version restores expected behaviour.

iii. Using a new profile or "refreshing" the existing user profile appears to bypass the problem

**Comment by justFlow** [comment]
Somehow I managed to solve the issue without refreshing Firefox and reinstalling all my addons.

Either due to
1) Installing Add-on Compatibility Reporter
2) Deactivating all non-compatible multiprocess addons
3) Following automatic activation of multiprocess Firefox/e10s
4) Installing Privacy Badger from https://addons.mozilla.org/de/firefox/addon/privacy-badger17/?src=userprofile (I had two PB addons installed in the meantime somehow, removed the old one with same version)
5) Manually activating hardware acceleration with 4 content processes
or a arbitrary permuation of above.

I did all the steps alltogether, so I can't name the discrete fix.

FF 55.0.1 (64-Bit)

**Comment by ghostwords** [comment]
This might be fixed now that Firefox 55 reached stable.

**Comment by ghostwords** [comment]
I'm going to close this for now as the underlying Firefox bug should be fixed as of Firefox 55.0.2: https://bugzilla.mozilla.org/show_bug.cgi?id=1373776#c18

**Comment by Muad-Dib** [comment]
Sorry to re-open this but I cannot test this on the very latest Firefox version as I am pinned to 53ESR.  Does the newer versions of Firefox fix this bug?

Only having spent a whole day starting with a fresh profile then adding in my most used addons and tweaks, I have to reverse my earlier findings that a fresh profile fixes this issue - it does not.

**Comment by ghostwords** [comment]
My understanding is this is fixed as of Firefox 55.0.2 (see [above comment](https://github.com/EFForg/privacybadger/issues/1295#issuecomment-324110414)).

**Comment by puttu** [comment]
55.0.3 here and I still have this issue on eBay. I didn't refresh the profile or reinstall anything though.

**Comment by puttu** [comment]
Indeed, I was able to replicate the issue as before.

I restarted Firefox in safe mode and clicked around at ebay.com -- the issue was gone. I installed your test add-on as instructed and clicked around some more -- the issue was back (pages did not refresh). I removed the add-on and everything started working as expected again.

**Comment by ghostwords** [comment]
OK, so it's the same issue, happening again in Firefox 55.0.3. We never did figure out the root cause, it just seemed to go away, but now it's back it seems.

**Comment by fredwu** [comment]
Hi,

To make things even more "interesting"... I am not even a user of Privacy Badger. But after some trial and error, I've discovered that Tampermonkey and uBlock Origin cause this issue too. I have to disable both of them in order to get Ebay to navigate. :\

**Comment by ghostwords** [comment]
@fredwu Ah, good news in the sense that the more visible the bug, the more likely is Firefox to fix it. Is https://github.com/gorhill/uBlock/issues/2981 the same issue?

**Comment by fredwu** [comment]
@ghostwords Hmm, that issue seems to be different, at least I couldn't reproduce it. And when reading @gorhill's comment, disabling all my legacy addons did not help. :(

**Comment by gorhill** [comment]
> From a support email:
> 
> >     I recently discovered that when PB is enabled in firefox it causes
> >     problems at ebay.co.uk. The search function is not working properly. It
> >     gets stuck. Also ebay functions like "worldwide" or "sort by" are not
> >     working. That happens even if PB is disabled for the site. However, if I
> >     completely disable the addon for firefox, ebay works fine.

Sounds like this could be this bug: <https://bugzilla.mozilla.org/show_bug.cgi?id=1379148>.

Looking at the page source, I do see instances of `document.write`: `view-source:https://www.ebay.co.uk/`.

**Comment by Vetrikay** [comment]
I would also like to report that this issue is now happening both with uBlock Origin and Privacy Badger.

**Comment by Muad-Dib** [comment]
> I would also like to report that this issue is now happening both with uBlock Origin and Privacy Badger.

Oh dear. I can also confirm that it's either addon now.  I had been running uBlock Origin previously when I reported my findings but it was only PB that was causing an issue on Ebay at that point.
(currently Privacy Badger 2017.7.24, uBlock Origin 1.14.4, FF 52.3 ESR)

**Comment by gorhill** [comment]
@Muad-Dib Do you have e10s disabled?

**Comment by Muad-Dib** [comment]
Apparently so although I wasn't aware this was the case.  I just had a look in about:support and found this: "Multiprocess Windows 	0/1 (Disabled by add-ons)"
The wording suggests an addon is responsible for this (not sure which one specifically).  I can list those I use if helpful.

I used to maintain my own user.js tweaks as well but recognized this has got out of date, so with the new profile build I modified a user.js that ghacks publish which contains stanzas for toggling e10s:

// 2650: start the browser in e10s mode (48+)
   // After restarting the browser, you can check whether it's enabled by visiting
   // about:support and checking that "Multiprocess Windows" = 1
   // use force-enable and extensions.e10sblocksenabling if you have add-ons
   // user_pref("browser.tabs.remote.autostart", true);
   // user_pref("browser.tabs.remote.autostart.2", true); // (FF49+)
   // user_pref("browser.tabs.remote.force-enable", true); // (hidden pref)
   // user_pref("extensions.e10sBlocksEnabling", false);

Please let me know if you want me to force on and/or there are any tests you want me to conduct.

**Comment by gorhill** [comment]
> "Multiprocess Windows 0/1 (Disabled by add-ons)"

Then this looks like an issue in Firefox, I can reproduce it _only_ with e10s enabled:

- <https://github.com/gorhill/uBlock/issues/2967>
- <https://bugzilla.mozilla.org/show_bug.cgi?id=1396486>

**Comment by Vetrikay** [comment]
Issue remains with FF 56.

**Comment by Muad-Dib** [comment]
FYI without any changes to the platforms listed in my post 5th August (#issuecomment-320452104), it seems ebay have made some changes to their website recently and as a consequence I am no longer experiencing any issues running Privacy Badger/uBlock with their website.
