### ISSUE TITLE
unpkg.com CDN blocked, causes sites that use CDN to fail by default

### ISSUE THREAD

**Issue by Nicktho** [EFForg/privacybadger#1354]
Unpkg is a CDN that hosts distributions of NPM packages. We currently use unpkg as a cdn for certain shared libraries between pages of ours and have noticed privacybadger has started to block the domain from loading the assets by default.

Is this a desired result or is this a bug? We will need to move CDNs if unpkg will continue to be blocked by default.

**Comment by Nicktho** [comment]
Example sites blocked: https://www.theweeklyreview.com.au/, https://www.allhomes.com.au/

![screen shot 2017-04-28 at 11 38 14 am](https://cloud.githubusercontent.com/assets/8622243/25510982/5e652f32-2c07-11e7-9aab-5392603a5e47.png)

**Comment by jesstelford** [comment]
unpkg is also the default CDN recommended by Facebook's wildly popular React.js framework: https://facebook.github.io/react/docs/installation.html#using-a-cdn

**Comment by Nicktho** [comment]
Also, here is the action map for the domain: 

```
```**** ACTION_MAP for unpkg.com
VM695:5 unpkg.com {
  "dnt": false,
  "heuristicAction": "block",
  "nextUpdateTime": 1493622041720,
  "userAction": ""
}
VM695:7 **** SNITCH_MAP for unpkg.com
VM695:9 unpkg.com [
  "localhost",
  "domain.com.au",
  "flexboxfroggy.com"
]```
```

**Comment by ghostwords** [comment]
Thanks for the excellent bug report! Could you check to see if you have any cookies set by `unpkg.com`? My guess is that you should see CloudFlare `__cfduid` cookies, which means this issue would be solved by #1237.

**Comment by ghostwords** [comment]
This bug should be fixed in Privacy Badger version 2017.6.13.1 (by #1403 and #1428). Please let me know if you run into it again with the new version.

**Comment by Nicktho** [comment]
thanks!

**Comment by metacubed** [comment]
@ghostwords, I can still see this issue in 2018.4.10.

unpkg.com shows up as blocked (red) for https://insights.newrelic.com. Could you please reopen this issue?

**Comment by ghostwords** [comment]
@metacubed Could you run the following script in your Badger's background page console and share what it prints out?
```javascript
(function () {
  const STR = "unpkg.com";
  console.log("**** ACTION_MAP for", STR);
  _.each(badger.storage.getBadgerStorageObject('action_map').getItemClones(), (obj, domain) => {
    if (domain.indexOf(STR) != -1) console.log(domain, JSON.stringify(obj, null, 2));
  });
  console.log("**** SNITCH_MAP for", STR);
  _.each(badger.storage.getBadgerStorageObject('snitch_map').getItemClones(), (sites, domain) => {
    if (domain.indexOf(STR) != -1) console.log(domain, JSON.stringify(sites, null, 2));
  });
}());
```
To get to the background page console in Chrome, visit `chrome://extensions`, make sure "Developer mode" is checked, click on the "background page" link in Privacy Badger's row, and select the Console tab.

In Firefox, visit `about:debugging`, enable add-on debugging, click Debug next to Privacy Badger, click the OK button on the popup warning about remote debugging, and enter the above script into the console after the >>.

**Comment by ghostwords** [comment]
Also, if you visit your browser's cookie management page (`chrome://settings/siteData` in Chrome) and search for "unpkg", do you see any cookies or HTML5 local storage entries?
