### ISSUE TITLE
Gallery images on Facebook are tiny with PrivacyBadger enabled on both Chrome and Firefox

### ISSUE THREAD

**Issue by Dyras** [EFForg/privacybadger#2214]
Greetings! For some reason, when you click a picture in the gallery under "Messenger" on Facebook, the pictures are always really small. This happens on both the **latest Firefox** and the **latest Chrome**, with the **latest PrivacyBadger** on both.

**How to reproduce**:
1. Go on here https://www.facebook.com/messages/t
2. Click a chat with an image you want to view
3. Click the image in the bottom right corner, where all Facebook images in that chat are stored
4. The image should be this "big": 
![image](https://user-images.githubusercontent.com/12563436/48301685-f694d380-e4f1-11e8-8793-af55b23c1105.png)
Note how it's opened in a separate tab instead of inside the Messenger tab
5. Deactivate PrivacyBadger on Facebook
6. Click the same image again
7. It's now this big: 
![image](https://user-images.githubusercontent.com/12563436/48301690-07dde000-e4f2-11e8-816d-de0fec32000c.png)
Note how it's opened in the same tab as Messenger. Just on top of the chat.

**Comment by ghostwords** [comment]
Hello and thank you for the bug report! I wonder if this is the same kind of issue as https://github.com/EFForg/privacybadger/issues/2181#issuecomment-427103320, where we remove too much from the link element while [removing tracking](https://github.com/EFForg/privacybadger/blob/60ddd1c6a2f92a9762478a9810aff070644683f2/src/js/firstparties/facebook.js#L15-L33), although maybe not, need to take a look.

**Comment by ghostwords** [comment]
@bcyphers Could you take a look please?

**Comment by Dyras** [comment]
@ghostwords @bcyphers Any news on this? It's been 3 months now. Facebook is a major website and this affects everyone using both PrivacyBadger and Facebook, and I'm getting pretty sick of it :(

**Comment by ghostwords** [comment]
We should have a fix released next week: #2307.

**Comment by ghostwords** [comment]
This should be fixed as of today's Privacy Badger update (version 2019.2.19).

**Comment by Dyras** [comment]
@ghostwords Unless I'm missing something, this is still happening.

Version info:
![image](https://user-images.githubusercontent.com/12563436/53097741-78998d00-3522-11e9-8bc9-faebb604a3e3.png)

What the pictures look like when I click them:
![image](https://user-images.githubusercontent.com/12563436/53097756-83ecb880-3522-11e9-9334-559b98871e77.png)

What the pictures should look like when I click them: 
![image](https://user-images.githubusercontent.com/12563436/53097815-9d8e0000-3522-11e9-913d-c007fd3d4f21.png)

**Comment by ghostwords** [comment]
@bcyphers Could you take a look please?

**Comment by ghostwords** [comment]
Does this happen on Firefox for Android only, or is it also an issue on the desktop?

**Comment by Dyras** [comment]
@ghostwords I'm using Chrome on Windows 10

**Comment by ghostwords** [comment]
I see, I got confused because those screenshots are from Android.

**Comment by Dyras** [comment]
@ghostwords Sorry, I should have been more clear :( I found the pictures on Reddit and sent them to someone

**Comment by bcyphers** [comment]
Sorry for the delay on this, I'll take a look this week.

**Comment by Dyras** [comment]
No problem! The fact that you guys are even responding to this speaks wonders for how great this project is.

**Comment by bcyphers** [comment]
I'm having some trouble duplicating this. Can you share your chrome version number?

**Comment by Dyras** [comment]
Version 73.0.3683.103 

Do you want me to try it on a fresh PortableApp of Firefox or Chrome or something?

**Comment by Dyras** [comment]
Also, it seems to more consistently happen if you scroll up in a conversation, rather than sending new pictures and clicking them.

**Comment by bcyphers** [comment]
Okay, I'm still having trouble replicating it on Ubuntu (work computer), but found something. If I left-click on a picture, the picture displays like normal (in the gallery view, full size). However, if I middle-click on the photo, or right-click -> "open in new tab," the photo opens in a new tab in tiny mode.

I can test this on Windows when I get home tonight.

> Also, it seems to more consistently happen if you scroll up in a conversation, rather than sending new pictures and clicking them.

Is this a non-deterministic thing? If so, how often does it happen? are there circumstances where it never or always happens?

**Comment by Dyras** [comment]
I deleted that comment because I couldn't reproduce that issue anymore.

However, the issue with the Shared Photos are still very reproducable on both MacOS and Windows 10.

Just click any sent message: 
![Skärmavbild 2019-04-12 kl  02 24 16](https://user-images.githubusercontent.com/12563436/56004176-237c2b00-5cca-11e9-9c7a-0bbc7fa52501.png)

**Comment by bcyphers** [comment]
Okay, now I'm using Chrome 73.0.3683.103 on Windows 10. Still not seeing the issue when I left-click a picture in the bottom right corner, with Privacy Badger enabled. Also no issue when I click on an in-line image in the message history after scrolling up for a while. Everything works okay in Firefox as well.

**Comment by bcyphers** [comment]
Ugh, still not seeing anything. I've tried clicking on photos uploaded by both me and others in the chat, both recent and old, and everything opens up in gallery view properly. Would you mind trying in an instance of Chrome with a fresh user profile?

And just to check, you're using the latest version of PB (2019.2.19)?

**Comment by Dyras** [comment]
I'm using 2019.2.19, yes.

I'm trying to reproduce it now. It was reproducable 100% of the time literally 20 minutes ago and now it's working as intended.

What the fuck :(

Will try to figure out what's causing it later. Maybe it's something that starts happening if you're on Facebook Messenger a really long time? I tend to have it open practically all day.

I'll try to figure it out tomorrow. I live in Europe so it's bedtime now :(

**Comment by bcyphers** [comment]
okay! let me know here if you figure out how to repro. Definitely know the pain of the Heisenbug.

**Comment by Dyras** [comment]
@bcyphers 
I've managed to figure it out!

You have to set the Facebook language to Swedish (Svenska) and it will start happening immediately afterwards.

**Comment by Dyras** [comment]
@bcyphers Any news on this? Just wondering.

**Comment by Dyras** [comment]
@bcyphers @ghostwords this is still happening with your language set to Swedish :(

Any cahnce for some love?

**Comment by ghostwords** [comment]
I'll take a look next week.

**Comment by ghostwords** [comment]
OK, I see what's going on. @bcyphers We thought we fixed this issue with #2307, and we did, for Facebook locales where the ARIA label for photos is set to "photo". Apparently, this label is localized. What! Yes. For example, `aria-label` is set to "Foto" *auf Deutsch*.

**Comment by mgziminsky** [comment]
That makes sense, aria attributes are used for accessibility tools like screen readers, so they would need to be localized. 

You may be able to whitelist `a._3m31` instead, or `a._3m31[aria-label]` to be a little more explicit if you wanted. It's possible that class could change frequently though, but it's also possible it won't, and I don't see any other options that would be any more reliable.
