### ISSUE TITLE
unable to download Privacy Badger onto Firefox because download corrupted.

### ISSUE THREAD

**Issue by Wordwizard** [EFForg/privacybadger#2392]
I was unable to download Privacy Badger onto Firefox because download corrupted.

**Comment by ghostwords** [comment]
Hello!

This was a Firefox bug that affected all Firefox extensions. The bug should now be fixed in the latest, supported versions of Firefox.

You can see the following link for more information and workarounds for older versions of Firefox:
https://blog.mozilla.org/addons/2019/05/04/update-regarding-add-ons-in-firefox/

Let me know if you have any questions, or if this isn't the same problem.

**Comment by ghostwords** [comment]
Duplicate of #2356.

**Comment by Wordwizard** [comment]
| 
| 
|  |

 |
| 
| This is not fixed. I have Firefox 66.0.2.
-- EXCELSIOR!
 

  |

 |
| 
|  |

 |

 |
| 
|  | Yahoo Mail Stationery |

 |

    On Sunday, June 16, 2019, 5:41:58 PM EDT, Alexei <notifications@github.com> wrote:  
 
 
Hello!

This was a Firefox bug that affected all Firefox extensions. The bug should now be fixed in the latest, supported versions of Firefox.

You can see the following link for more information and workarounds for older versions of Firefox:
https://blog.mozilla.org/addons/2019/05/04/update-regarding-add-ons-in-firefox/

Let me know if you have any questions, or if this isn't the same problem.

**Comment by ghostwords** [comment]
Right, but the fix is in Firefox 66.0.5. Can you update to the latest version of Firefox?

**Comment by Wordwizard** [comment]
| 
| 
|  |

 |
| 
| How do I do that?
-- EXCELSIOR! 

  |

 |
| 
|  |

 |

 |
| 
|  | Yahoo Mail Stationery |

 |

    On Monday, June 17, 2019, 11:26:37 AM EDT, Alexei <notifications@github.com> wrote:  
 
 
Right, but the fix is in Firefox 66.0.5. Can you update to the latest version of Firefox?

**Comment by ghostwords** [comment]
Can you install the latest version from https://firefox.com?

**Comment by Wordwizard** [comment]
| 
| 
|  |

 |
| 
| Yes. Problem solved. Thanks!
-- EXCELSIOR!
Is this from Eleanor?(Probably, unless it's from her alter-ego Andrea.) 

  |

 |
| 
|  |

 |

 |
| 
|  | Yahoo Mail Stationery |

 |

    On Monday, June 17, 2019, 3:35:06 PM EDT, Alexei <notifications@github.com> wrote:  
 
 
Can you install the latest version from https://firefox.com?
