### ISSUE TITLE
Privacy Badger on Firefox prevents images and media from loading inside Element (matrix) chats

### ISSUE THREAD

**Issue by ilyagr** [EFForg/privacybadger#3113]
The symptoms seem to be very similar to the ones in https://github.com/element-hq/element-web/issues/28370. Privacy Badger says that "no trackers were disabled", so it makes it *seem* like it's not doing anything, but disabling the extension for `app.element.io` makes Element work correctly again.

**Update:** Here's a screenshot of what I saw (note the grey rectangles instead of 2 of the images, and the loading circle instead of a 3rd image; this was the permanent state of the page rather than something only shown for a moment)

![Image](https://github.com/user-attachments/assets/7daca07b-3d02-4b2b-b770-cfa1a358234f)

**Comment by lenacohen** [comment]
Thanks for opening an issue! Could you provide us with steps to reproduce? Does the issue go away when you disable Privacy Badger on the site `app.element.io` and occur again when you re-enable Privacy Badger on that site?

**Comment by ilyagr** [comment]
> Does the issue go away when you disable Privacy Badger on the site `app.element.io` and occur again when you re-enable Privacy Badger on that site?

Yes, though I had to reload the site with `Shift+Reload` (on Firefox) for the issue to reoccur after enabling privacy badger.

> Could you provide us with steps to reproduce? 

Go to a matrix chat with images or upload an image to a matrix chat (paste one from a clipboard). If the issue does not occur, try reloading the site with `Shift+Reload`.

> Do you have local learning enabled or are you using Privacy Badger with the default settings?

Default settings.

**Comment by ghostwords** [comment]
Disabling Privacy Badger reloads the page and makes it look like the issue is fixed, but it's not, as I can reproduce the problem with another hard reload. It's just the same as reloading the page after reproducing the issue with no extension installed.

**Comment by ilyagr** [comment]
So, without Privacy badger, can you fix the issue by reloading the page again? 

With Privacy Badger, my experience was that the issue persisted no matter what I did, until I disabled Privacy Badger for the site. I spent quite a bit of time trying to fix it before I tried disabling PB, with no success.
